Product planning
flowforge/handbook pull request #86
Opened 2022-07-11 11:06 UTC by sammachin

details of what we've discussed over our previous product calls.

Still TODO is to add the Business Rules around billing but that will follow in a separate PR

2022-07-11 15:25 UTC, knolleary reviewed
Typo fix suggested, but that aside, I think this properly reflects the discussions we've had and gets it documented properly in the right place. 👍🏻

2022-07-11 15:25 UTC, knolleary commented on product/plan.md
> +A more detailed breakdown of the pricing and split between our Open Source and Enterprice Editions is on the [pricing pricicpes](pricing.md) page
```suggestion
A more detailed breakdown of the pricing and split between our Open Source and Enterprise Editions is on the [pricing principles](pricing.md) page
```

2022-07-13 11:21 UTC, ZJvandeWeg requested changes

2022-07-13 11:21 UTC, ZJvandeWeg commented on product/versioning.md
> +- We have the admin features required to manage the platform at an appropriate scale.
I agree with this list. My doubt and fear is still that this becomes a large chunck of work that's not tightly enough scoped. With that we don't ship fast enough. Hope that makes sense?

I tried to circumvent this with #85. So if we timebox the release with this list, I'm supportive.

2022-07-13 11:21 UTC, ZJvandeWeg commented on product/versioning.md
> +- We have a suitable licensing model in place
Minor note: for me just project pricing might even suffice for 1.0. Devices would be great, teams IMO is a stretch goal.

Reason being that building a feature gap between tiers takes time. Building a gap on 3 axis is taking exponentially more time is my gut feeling.

2022-07-13 14:23 UTC, sammachin commented on product/versioning.md
> +The 1.x line will be supported for at least 12 months from the first release of 1.0, this means that customers may need to update to a 1.x release in order to receive fixes and new features. Even aft
yes thats better wording

2022-07-26 10:20 UTC, merged